import ollama

class Generator:
    def __init__(self, model_name="llama3.2:3b"):
        """Initializes the Generator with a specified model name and an OpenAI client.
        Args:
            model_name (str): The name of the model to be used for generating answers.
        """
        self.model = model_name

    def create_prompt(self, question, chunks):
        """Creates a prompt for the model based on the question and provided context chunks.
        Args:
            question (str): The question to be answered.
            chunks (list): A list of chunk dictionaries, each containing text and metadata.
        Returns:
            str: A formatted prompt string that includes the context and the question."""
        context = "\n\n".join([chunk["text"] for chunk in chunks])
        prompt = f"""You are Track Atlas, an expert assistant for track and field.
        Answer the question using only the provided context.
        If the answer is not in the context, say you do not know.

        Context:
        {context}

        Question:
        {question}
        """
        return prompt

    def generate_answer(self, question, chunks):
        """Generates an answer to a question based on the provided context chunks.
        Args:
            question (str): The question to be answered.
            chunks (list): A list of chunk dictionaries, each containing text and metadata.
        Returns:
            str: The answer generated by the model.
        """
        prompt = self.create_prompt(question, chunks)

        response = ollama.chat(
            model=self.model,
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        return response["message"]["content"]