class RAGPipeline:
    def __init__(self, retriever, generator):
        """Initializes the RAGPipeline with a retriever and a generator.
        Args:
            retriever (Retriever): An instance of the Retriever class for retrieving relevant documents.
            generator (Generator): An instance of the Generator class for generating answers based on retrieved documents.
        """
        self.retriever = retriever
        self.generator = generator

    def ask(self, question, k=5):
        """Asks a question and retrieves relevant chunks, then generates an answer.
        Args:
            question (str): The question to be answered.
            k (int): The number of relevant chunks to retrieve.
        Returns:
            str: The answer generated by the model."""
        chunks = self.retriever.retrieve(question, k=k)
        if not chunks:
            return "I do not have enough information to answer this question."

        answer = self.generator.generate_answer(question, chunks)
        return answer
